#spring.application.name=journal-app
#
##spring.data.mongodb.host=localhost
##spring.data.mongodb.port=27017
##spring.data.mongodb.database=journaldb
#
#
#spring.data.mongodb.uri=mongodb://localhost:27017/journaldb

#spring.data.mongodb.uri=mongodb+srv://samratsaha9635:pC5AbWj6S1C2TCKI@cluster0.nnfmxfl.mongodb.net/journaldb?retryWrites=true&w=majority&appName=Cluster0

#spring.data.mongodb.auto-index-creation=true



spring.application.name=journal-app

#spring.data.mongodb.uri=mongodb://localhost:27017/journaldb
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.auto-index-creation=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend.base-url=http://localhost:8080
server.port=${PORT:8080}

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000